apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restream-backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: beyondspeedrun.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restream-backend
                port:
                  number: 80
