apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /mnt/data
    server: 192.168.1.17
  persistentVolumeReclaimPolicy: Retain
